[toolchain]
anchor_version = "0.30.1"    # `anchor-cli` version to use(requires `avm`)
solana_version = "1.18.22"    # Solana version to use(applies to all Solana tools)

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending_pool = "Dc3diDtBztbtXgnLtHHn8MnPjjiGHBK5AfxQ5GHWGSXQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# [[test.validator.clone]]
# address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"

# [test.validator]
# url = "https://api.mainnet-beta.solana.com"     # This is the url of the cluster that accounts are cloned from (See `test.validator.clone`).
